services:
  shard0:
    image: postgres:15
    container_name: shard0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard0
    ports:
      - "5433:5432"
    restart: always

  shard1:
    image: postgres:15
    container_name: shard1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard1
    ports:
      - "5434:5432"
    restart: always

  shard2:
    image: postgres:15
    container_name: shard2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard2
    ports:
      - "5435:5432"
    restart: always
